test: add support for bios boot mode

diff --git a/test/install_from_live b/test/install_from_live
--- a/test/install_from_live
+++ b/test/install_from_live
@@ -4,15 +4,43 @@ set -xeuo pipefail
 
 export PATH="/root/arch-ostree:$PATH"
 
+# shellcheck source=/lib/common.sh
 source /root/arch-ostree/lib/common.sh
 
 disk="/dev/disk/by-id/ata-QEMU_HARDDISK_QM00002"
-part_efi="/dev/disk/by-partlabel/efi"
-part_boot="/dev/disk/by-partlabel/boot"
-part_root="/dev/disk/by-partlabel/root"
-supported_modes=(
+supported_part_schemes=(
 	plain
 	lukspart
+)
+supported_boot_modes=(
+	bios
+	uefi
+)
+long_opts=(
+	part-scheme:
+)
+part_scheme=plain
+if [ -f /sys/firmware/efi/fw_platform_size ]; then
+	boot_mode=uefi
+else
+	boot_mode=bios
+fi
+tasks=(
+	cleanup
+	increase_cowspace
+	pacman_refresh
+	prepare_disk
+	mount
+	prepare_live_env
+	init_ostree
+	build_builder_container
+	build_rootfs
+	commit_rootfs
+	create_deployment_env
+	grub_install
+	deploy
+	install_ssh_key
+	write_fstab
 )
 
 task_cleanup() {
@@ -29,13 +57,15 @@ task_pacman_refresh() {
 }
 
 task_prepare_disk() {
-	sfdisk -w always "$disk" < "/root/arch-ostree/test/layout.sfdisk"
+	sfdisk -w always "$disk" < "/root/arch-ostree/test/layout-$boot_mode.sfdisk"
 	sleep 1
 
-	mkfs.vfat -F32 "$part_efi"
+	if [ "$boot_mode" = "uefi" ]; then
+		mkfs.vfat -F32 "$part_efi"
+	fi
 	mkfs.ext4 "$part_boot"
 
-	case "$mode" in
+	case "$part_scheme" in
 		plain)
 			mkfs.ext4 "$part_root"
 		;;
@@ -48,7 +78,7 @@ task_prepare_disk() {
 }
 
 task_mount() {
-	case "$mode" in
+	case "$part_scheme" in
 		plain)
 			mount "$part_root" /mnt
 		;;
@@ -64,8 +94,10 @@ task_mount() {
 	mkdir -p /mnt/boot
 	mount "$part_boot" /mnt/boot
 
-	mkdir -p /mnt/efi
-	mount "$part_efi" /mnt/efi
+	if [ "$boot_mode" = "uefi" ]; then
+		mkdir -p /mnt/efi
+		mount "$part_efi" /mnt/efi
+	fi
 }
 
 task_prepare_live_env() {
@@ -115,10 +147,17 @@ deploy_cmd() {
 }
 
 task_grub_install() {
-	deploy_cmd grub-install \
-		--target x86_64-efi \
-		--efi-directory /efi \
-		--bootloader-id=GRUB
+	case "$boot_mode" in
+		bios)
+			deploy_cmd grub-install --target i386-pc "$disk"
+		;;
+		uefi)
+			deploy_cmd grub-install \
+				--target x86_64-efi \
+				--efi-directory /efi \
+				--bootloader-id=GRUB
+		;;
+	esac
 
 	ln -sf ../loader/grub.cfg /mnt/boot/grub/grub.cfg
 }
@@ -127,7 +166,7 @@ task_deploy() {
 	rootuuid="$(blkid -o value -s UUID "$part_root")"
 	kargs=()
 
-	case "$mode" in
+	case "$part_scheme" in
 		plain)
 			kargs+=(
 				--karg=root=UUID="$rootuuid"
@@ -135,12 +174,11 @@ task_deploy() {
 		;;
 		lukspart)
 			kargs+=(
-				--karg=rd.luks.name=$rootuuid=root
+				--karg="rd.luks.name=$rootuuid=root"
 				--karg=root=/dev/mapper/root
 			)
 		;;
 	esac
-
 
 	deploy_cmd ostree admin deploy \
 		--os=archlinux \
@@ -183,26 +221,28 @@ task_group_prepare_existing() {
 	task_prepare_live_env
 }
 
-tasks=(
-	cleanup
-	increase_cowspace
-	pacman_refresh
-	prepare_disk
-	mount
-	prepare_live_env
-	init_ostree
-	build_builder_container
-	build_rootfs
-	commit_rootfs
-	create_deployment_env
-	grub_install
-	deploy
-	install_ssh_key
-	write_fstab
-)
+if ! temp=$(getopt -o '+' --long "$(join_by , "${long_opts[@]}")" -- "$@"); then
+	die "Invalid arguments"
+fi
 
-mode="$1"
-shift
+eval set -- "$temp"
+while true; do
+	case "$1" in
+		'--part-scheme')
+			name="$(arg_to_varname "$1")"
+			printf -v "$name" "%s" "$2"
+			shift 2
+			continue
+		;;
+		'--')
+			shift
+			break
+		;;
+		*)
+			die "BUG: Unexpected argument: $1"
+		;;
+	esac
+done
 
 if [ $# -ne 0 ]; then
 	tasks=()
@@ -216,7 +256,6 @@ if [ $# -ne 0 ]; then
 
 		tasks+=("$arg")
 	done
-
 fi
 
 args=("$@")
@@ -227,9 +266,25 @@ for task in "${tasks[@]}"; do
 	fi
 done
 
-if [[ ! "${supported_modes[@]}" =~ "$mode" ]]; then
-	die "Unsupported mode: $mode"
+if [[ ! ${supported_part_schemes[*]} =~ $part_scheme ]]; then
+	die "Unsupported partition scheme: $part_scheme"
 fi
+
+if [[ ! ${supported_boot_modes[*]} =~ $boot_mode ]]; then
+	die "Unsupported boot_mode: $boot_mode"
+fi
+
+case "$boot_mode" in
+	bios)
+		part_boot="$disk-part1"
+		part_root="$disk-part2"
+	;;
+	uefi)
+		part_efi="/dev/disk/by-partlabel/efi"
+		part_boot="/dev/disk/by-partlabel/boot"
+		part_root="/dev/disk/by-partlabel/root"
+	;;
+esac
 
 for task in "${tasks[@]}"; do
 	"task_$task"
diff --git a/test/start_vm b/test/start_vm
--- a/test/start_vm
+++ b/test/start_vm
@@ -3,6 +3,8 @@
 set -xeuo pipefail
 
 git_dir="$(git rev-parse --show-toplevel)"
+source "$git_dir/lib/common.sh"
+
 test_dir="$git_dir/test"
 cache_dir="$test_dir/cache"
 disk_file="$cache_dir/disk.qcow2"
@@ -12,39 +14,35 @@ iso_unverified="$cache_dir/arch-unverified.iso"
 ovmf_vars="$cache_dir/OVMF_VARS.4m.fd"
 ssh_key="$cache_dir/id_rsa"
 cloud_init_iso="$cache_dir/cloud-init.iso"
-if [ "$1" == "1" ]; then
-	with_cdrom=true
-else
-	with_cdrom=false
-fi
+with_cdrom=true
+with_uefi=true
+long_opts=(
+	with-cdrom:
+	with-uefi:
+)
 
-mkdir -p "$cache_dir"
+download_arch_iso() {
+	if [ ! -f "$iso" ]; then
+		if [ ! -f "$iso_unverified" ]; then
+			curl \
+				-Lo "$iso_unverified" \
+				"$mirror/latest/archlinux-x86_64.iso"
+		fi
+		if [ ! -f "$iso_unverified.sig" ]; then
+			curl \
+				-Lo "$iso_unverified.sig" \
+				"$mirror/latest/archlinux-x86_64.iso.sig"
+		fi
 
-if [ ! -f "$iso" ]; then
-	if [ ! -f "$iso_unverified" ]; then
-		curl \
-			-Lo "$iso_unverified" \
-			"$mirror/latest/archlinux-x86_64.iso"
+		sq --force wkd get pierre@archlinux.org -o "$cache_dir/release-key.pgp"
+		sq verify \
+			--signer-file "$cache_dir/release-key.pgp" \
+			--detached "$iso_unverified.sig" \
+			"$iso_unverified"
+
+		mv "$iso_unverified" "$iso"
 	fi
-	if [ ! -f "$iso_unverified.sig" ]; then
-		curl \
-			-Lo "$iso_unverified.sig" \
-			"$mirror/latest/archlinux-x86_64.iso.sig"
-	fi
-
-	sq --force wkd get pierre@archlinux.org -o "$cache_dir/release-key.pgp"
-	sq verify \
-		--signer-file "$cache_dir/release-key.pgp" \
-		--detached "$iso_unverified.sig" \
-		"$iso_unverified"
-
-	mv "$iso_unverified" "$iso"
-fi
-
-if [ ! -f "$ssh_key" ]; then
-	ssh-keygen -t rsa -N "" -C "test" -f "$ssh_key"
-fi
-
+}
 
 create_cloud_init_iso() {
 	echo ''> "$cache_dir/meta-data"
@@ -72,9 +70,48 @@ EOF
 		"$cache_dir/network-config"
 }
 
-if [ ! -f "$ovmf_vars" ]; then
-	cp /usr/share/edk2/x64/OVMF_VARS.4m.fd "$ovmf_vars"
+if ! temp=$(getopt -o '' --long "$(join_by , "${long_opts[@]}")" -- "$@"); then
+	die "Invalid arguments"
 fi
+
+eval set -- "$temp"
+while true; do
+	case "$1" in
+		'--with-cdrom'|\
+		'--with-uefi')
+			name="$(arg_to_varname "$1")"
+
+			case "$2" in
+				'true'|'1'|'yes')
+					eval "$name=true"
+				;;
+				'false'|'0'|'no')
+					eval "$name=false"
+				;;
+				*)
+					die "Unsupported bool value: $2"
+				;;
+			esac
+
+			shift 2
+			continue
+		;;
+		'--')
+			shift
+			break
+		;;
+		*)
+			die "BUG: Unexpected argument: $1"
+		;;
+	esac
+done
+
+mkdir -p "$cache_dir"
+
+if [ ! -f "$ssh_key" ]; then
+	ssh-keygen -t rsa -N "" -C "test" -f "$ssh_key"
+fi
+
 
 if [ ! -f "$disk_file" ]; then
 	qemu-img create -f qcow2 "$disk_file" 10G
@@ -82,10 +119,23 @@ fi
 
 cloud_init_args=()
 if [ $with_cdrom = true ]; then
+	download_arch_iso
 	create_cloud_init_iso
 	cloud_init_args+=(
 		-cdrom "$iso"
-		-drive file="$cloud_init_iso",format=raw
+		-drive file="$cloud_init_iso,format=raw"
+	)
+fi
+
+extra_args=()
+if [ $with_uefi = true ]; then
+	if [ ! -f "$ovmf_vars" ]; then
+		cp /usr/share/edk2/x64/OVMF_VARS.4m.fd "$ovmf_vars"
+	fi
+
+	extra_args+=(
+		-drive "if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd"
+		-drive "if=pflash,format=raw,file=$ovmf_vars"
 	)
 fi
 
@@ -94,7 +144,6 @@ qemu-system-x86_64 \
 	-drive file="$disk_file,format=qcow2" \
 	-enable-kvm \
 	-cpu host \
-	-drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd \
-	-drive if=pflash,format=raw,file=$ovmf_vars \
 	-m 4G \
+	"${extra_args[@]}" \
 	-nic user,hostfwd=tcp::60022-:22
