cleanup

diff --git a/arch-ostree b/arch-ostree
--- a/arch-ostree
+++ b/arch-ostree
@@ -1,73 +1,164 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -xeuo pipefail
 
-gitdir="$(dirname "$(readlink -f "$0")")"
-source "$gitdir/lib/common.sh"
+scriptdir="$(dirname "$(readlink -f "$0")")"
+lib_dir="$scriptdir/lib"
+share_dir="$scriptdir/share"
+source "$lib_dir/common.sh"
 
 builder_tag="archlinux-ostree-builder"
-rootfs_tag="archlinux-ostree"
+rootfs_tag="archlinux-ostree-rootfs"
 ostree_repo="/sysroot/ostree/repo"
 podman_build_cache=false
 
 usage() {
   cat <<EOF
-usage: ${0##*/} [options] [command] [arg...]
+USAGE: ${0##*/} [options] [command] [arg...]
 
-  <bool> is a value of 0, false, no, 1, true or yes.
+<bool> is a value of 0, false, no, 1, true or yes.
 
-  Options:
-    --podman-build-cache <bool>    Enable/Disable podman build cache. Boolean.
-                                   Default: no.
-    --pacman-cache <path>          Path to a persistent pacman package cache.
-                                   Default: undefined, thus the pacman cache
-                                   is disabled.
-    --builder-tag <name>          Name of the tag to use for the pacstrap
-                                   container.
-                                   Default: archlinux-pacstrap.
-    --rootfs-tag <name>            Name of the tag to use for the rootfs
-                                   container.
-                                   Default: archlinux-ostree-base.
-    --rootfs-containerfile <path>  Path to the Containerfile used for building
-                                   the rootfs container.
-    --rootfs-dir <path>            Path to the directory where the rootfs will
-                                   be created in.
-    --ostree-repo <path>           Path to the ostree repository.
-                                   Default: /sysroot/ostree/repo.
+COMMON OPTIONS:
+    --aur-dir
+        Path to the directory where built AUR packages are stored.
+    --builder-tag <name>
+        Name of the tag to use for the pacstrap container.
+        Default: archlinux-ostree-builder
+    --deploy-env-dir <path>
+        Path to the directory that's used as the deployment environment.
+    --ostree-repo <path>
+        Path to the ostree repository.
+        Default: /sysroot/ostree/repo
+    --podman-build-cache <bool>
+        Enable/Disable podman build cache. Boolean.
+        Default: no.
+    --pacman-cache <path>
+        Path to a persistent pacman package cache. This controls both podmans
+        --no-cache option and buildahs BUILDAH_LAYERS environment variable.
+        Default: undefined, thus the pacman cache is disabled.
+    --sysroot-dir
+        Path to the directory where your rootfs and all your partitions
+        (like boot or efi) are mounted.
+    --help
+        Print this help message
 
-    --help                         Print this help message
+ROOTFS OPTIONS:
+    --rootfs-dir <path>
+       Path to the directory where the rootfs will be created in.
 
-  Commands:
-    build_builder_container         (Re-)Build pacstrap container that's used
-                                     by the other commands and tag it with
-				     --builder-tag.
-    build_rootfs_container           Build rootfs container from
-                                     --rootfs-containerfile and tag it with
-                                     --rootfs-tag.
-    enter_rootfs_container [arg...]  Enter --rootfs-tag container. All changes
-                                     will be lost.
-    commit_rootfs_container [arg...] Commit --rootfs-tag container to
-                                     --ostree-repo. This tool provides --repo
-                                     and --tree-dir to ostree commit.
-                                     Everything else (like branch name) can and
-                                     has to be provided by you.
-    pacstrap_rootfs_directory [pkg...] Run pacstrap on --rootfs-dir. If the
-                                       directory exists, it will NOT be deleted.
-				       [pkg...] will be passed to packstrap and
-				       must contain the packages that shall be
-				       installed.
-    enter_rootfs_directory [arg...]  Enter --rootfs-dir. All changes will be
-                                     lost.
-    commit_rootfs_directory [arg...] Commit --rootfs-dir container to
-                                     --ostree-repo. This tool provides --repo
-                                     and --tree-dir to ostree commit.
-                                     Everything else (like branch name) can and
-                                     has to be provided by you.
+CONTAINER OPTIONS:
+    --rootfs-containerfile <path>
+        Path to the Containerfile used for building the rootfs container.
+    --rootfs-tag <name>
+        Name of the tag to use for the rootfs container.
+        Default: archlinux-ostree-rootfs
 
+COMMON COMMANDS:
+    prepare_live_env
+        Prepare currently booted live ISO environment for setting up a new
+        ostree installation.
+    build_builder_container
+        (Re-)Build pacstrap container that's used by the other commands and tag
+        it with --builder-tag.
+    deploy_env -- [arg...]
+        Spawn a shell with a deployment at --deploy-env-dir as the rootfs.
+        This can be used to install the bootloader and create your first
+        deployment from the arch live ISO.
+        The shell runs inside a chroot that looks similar to a booted ostree
+        environment.
+
+CONTAINER COMMANDS:
+    build_rootfs_container
+        Build rootfs container from --rootfs-containerfile and tag it with
+        --rootfs-tag.
+    commit_rootfs_container -- [arg...]
+        Commit --rootfs-tag container to --ostree-repo. This tool provides
+        --repo and --tree-dir to "ostree commit". Everything else
+        (like branch name) can and has to be provided by you.
+    enter_rootfs_container -- [arg...]
+        Enter --rootfs-tag container. All changes will be lost.
+
+ROOTFS COMMANDS:
+    build_rootfs_directory <path>
+        Builds a rootfs directory at --rootfs-dir using the script-file at
+        <path>. See BUILD_SCRIPT_FORMAT for details on the format of that file.
+        <path> is deleted recursively before building the new rootfs.
+    commit_rootfs_directory -- [arg...]
+        Commit --rootfs-dir container to --ostree-repo. This tool provides
+        --repo and --tree-dir to ostree commit. Everything else
+        (like branch name) can and has to be provided by you.
+    enter_rootfs_directory -- [arg...]
+        Enter --rootfs-dir. All changes will be lost.
+    pacstrap_rootfs_directory [pkg...]
+        Run pacstrap on --rootfs-dir. If the directory exists, it will NOT be
+        deleted. [pkg...] will be passed to pacstrap and must contain the
+        packages that shall be installed.
+
+BUILD_SCRIPT FORMAT:
+    A build script is a shell-script that's sourced by another shell-script.
+    It can be used to define everything that's needed to build your rootfs in a
+    single file.
+    This works similar to PKGBUILD in that it has to define certain variables
+    and functions. The script can be sourced multiple times and into different
+    environments(like containers). So don't expect any variables or files to
+    stay around in between function calls.
+
+    VARIABLES:
+      packages
+        A bash array that contains the packages you want to install using
+        pacstrap.
+      aur_packages
+        A bash array that contains the packages you want to install from the
+        AUR. They are built inside a clean --builder-tag container, so you
+        don't need to worry about leaving behind trash in your actual rootfs.
+        Currently, they are build manually using makepkg, so you have to make
+        sure to include dependent packages that are only available in the AUR
+        as well. The packages are built in the order they are defined.
+
+    FUNCTIONS:
+      prepare
+        This is called after creating the rootfs directory, but before calling
+        pacstrap. It can be used to copy files like mkinitcpio.conf that will
+        be already be used by pacstrap.
+        It's called from the environment that arch-ostree runs in. The path to
+        the rootfs directory is stored in the variable "rootfs".
+      post_install_early
+        This is called after pacstrap inside a container that uses the
+        pacstrapped directory as it's rootfs. This can be used to write the
+        mirrorlist or init and populate the pacman keys which may be needed if
+        you want to install AUR packages(which are installed after this step).
+      post_install
+        Called after both post_install_early and installing AUR packages. This
+        can be used for common post installation steps like generating locales
+        or enabling systemd services.
 EOF
 }
 
+prepare_live_env() {
+	msg "Install required packages"
+	pacman \
+		--needed \
+		--noconfirm \
+		-S \
+		ostree \
+		podman
+
+	msg "Patch storage.conf"
+	sed -i \
+		-e 's|^\(graphroot\s*=\s*\).*|\1"/mnt/setup/container-storage"|g' \
+		/etc/containers/storage.conf
+
+	msg "Patch containers.conf"
+	sed -i \
+		-e 's|^# \(image_copy_tmp_dir\s*=\s*\).*|\1"/mnt/setup/container-tmp"|g' \
+		/etc/containers/containers.conf
+
+	mkdir -p "/mnt/setup/container-tmp"
+}
+
 pacstrap_rootfs_directory() {
+	# Without the increased pids-limit, pacstrap may fail at verifying
+	# package integrity.
 	podman run \
 		--pids-limit 4096 \
 		--cap-add sys_admin \
@@ -80,7 +171,7 @@ pacstrap_rootfs_directory() {
 		pacstrap -c -G -M /mnt "$@"
 }
 
-deploy_initial() {
+deploy_env() {
 	# We want to mount everything that the user has mounted at
 	# `sysroot_dir`(usually /mnt). This gives us all of the bootloader
 	# partitions.
@@ -94,27 +185,27 @@ deploy_initial() {
 		--output TARGET \
 		| tail -n +2)"
 
-	mkdir -p "$rootfs_dir/etc"
+	mkdir -p "$deploy_env_dir/etc"
 
-	mount -o ro,bind "$rootfs_dir" "$rootfs_dir"
-	mount -o ro,bind "$rootfs_dir/usr/etc" "$rootfs_dir/etc"
+	mount -o ro,bind "$deploy_env_dir" "$deploy_env_dir"
+	mount -o ro,bind "$deploy_env_dir/usr/etc" "$deploy_env_dir/etc"
 
 	for path in /run /tmp /var; do
-		mount -t tmpfs tmpfs "${rootfs_dir}${path}"
+		mount -t tmpfs tmpfs "${deploy_env_dir}${path}"
 	done
 
 	for path in /dev /proc /sys; do
-		mount --rbind "$path" "${rootfs_dir}${path}"
+		mount --rbind "$path" "${deploy_env_dir}${path}"
 	done
 
-	mount -o rw,bind "$sysroot_dir" "${rootfs_dir}/sysroot"
+	mount -o rw,bind "$sysroot_dir" "${deploy_env_dir}/sysroot"
 
 	while read -r source; do
 		target="$(realpath --relative-to="$sysroot_dir" "$source")"
-		mount -o rw,bind "$source" "${rootfs_dir}/$target"
+		mount -o bind "$source" "${deploy_env_dir}/$target"
 	done <<< "$findmnt_output"
 
-	chroot "$rootfs_dir" "${args[@]}"
+	chroot "$deploy_env_dir" "${args[@]}"
 }
 
 build_rootfs_directory() {
@@ -133,10 +224,9 @@ build_rootfs_directory() {
 			"${pacman_cache_args[@]}" \
 			--rm -it \
 			-v "$aur_dir:/tmp/aur" \
-			-v "$gitdir:/tmp/work" \
-			-w /tmp/work \
-			archlinux-pacstrap \
-			/tmp/work/lib/build_aur_packages \
+			-v "$lib_dir/build_aur_packages:/tmp/script" \
+			"$builder_tag" \
+			/tmp/script \
 			"${aur_packages[@]}"
 
 		post_install_args+=(-v "$aur_dir:/tmp/aur")
@@ -165,7 +255,8 @@ build_rootfs_directory() {
 		--tmpfs /run \
 		-v "$build_scriptdir:/tmp/work" \
 		-v "$build_script:/tmp/script" \
-		-v "$gitdir/lib/build_rootfs_post_install:/tmp/entrypoint" \
+		-v "$lib_dir/common.sh:/tmp/common.sh" \
+		-v "$lib_dir/build_rootfs_post_install:/tmp/entrypoint" \
 		-w /tmp/work \
 		--entrypoint /tmp/entrypoint \
 		--rootfs "$rootfs"
@@ -174,10 +265,11 @@ build_rootfs_directory() {
 long_opts=(
 	aur-dir:
 	builder-tag:
+	deploy-env-dir:
 	help
 	ostree-repo:
-	podman-build-cache:
 	pacman-cache:
+	podman-build-cache:
 	rootfs-containerfile:
 	rootfs-dir:
 	rootfs-tag:
@@ -192,9 +284,10 @@ while true; do
 	case "$1" in
 		'--aur-dir'|\
 		'--builder-tag'|\
+		'--deploy-env-dir'|\
 		'--ostree-repo'|\
 		'--pacman-cache'|\
-		'--rootfs-container'|\
+		'--rootfs-containerfile'|\
 		'--rootfs-dir'|\
 		'--rootfs-tag'|\
 		'--sysroot-dir')
@@ -258,32 +351,12 @@ fi
 
 case "$command" in
 	'prepare_live_env')
-		msg "Install required packages"
-		pacman \
-			--needed \
-			--noconfirm \
-			-S \
-			fuse-overlayfs \
-			git \
-			ostree \
-			podman
-
-		msg "Patch storage.conf"
-		sed -i \
-		    -e 's|^\(graphroot\s*=\s*\).*|\1"/mnt/setup/container-storage"|g' \
-		    /etc/containers/storage.conf
-
-		msg "Patch containers.conf"
-		sed -i \
-		    -e 's|^# \(image_copy_tmp_dir\s*=\s*\).*|\1"/mnt/setup/container-tmp"|g' \
-		    /etc/containers/containers.conf
-
-		mkdir -p "/mnt/setup/container-tmp"
+		prepare_live_env
 	;;
 	'build_builder_container')
 		podman build \
 			"${podman_build_cache_args[@]}" \
-			-f "$gitdir/share/Containerfile.builder" \
+			-f "$share_dir/Containerfile.builder" \
 			-t "$builder_tag"
 	;;
 
@@ -308,7 +381,8 @@ case "$command" in
 			--security-opt apparmor=unconfined \
 			--mount "type=image,src=localhost/$rootfs_tag,dst=/mnt-lower" \
 			--mount "type=bind,src=$ostree_repo,dst=/sysroot/ostree/repo" \
-			-v "$gitdir:/opt:ro" \
+			-v "$lib_dir:/opt/share:ro" \
+			-v "$share_dir:/opt/share:ro" \
 			--rm -it \
 			"localhost/$builder_tag" \
 			/opt/lib/commit_rootfs "$@"
@@ -338,15 +412,16 @@ case "$command" in
 			--security-opt apparmor=unconfined \
 			--mount "type=bind,src=$rootfs_dir,dst=/mnt-lower,ro" \
 			--mount "type=bind,src=$ostree_repo,dst=/sysroot/ostree/repo" \
-			-v "$gitdir:/opt:ro" \
+			-v "$lib_dir:/opt/lib:ro" \
+			-v "$share_dir:/opt/share:ro" \
 			--tmpfs /overlay \
 			--rm -it \
 			"localhost/$builder_tag" \
 			/opt/lib/commit_rootfs "$@"
 	;;
-	'deploy_initial')
+	'deploy_env')
 		args=("$@")
-		unshare -m bash -c "set -euo pipefail; $(declare_all); deploy_initial"
+		unshare -m bash -c "set -euo pipefail; $(declare_all); deploy_env"
 	;;
 	*)
 		die "Unsupported command: ${command}"
